"""make_stubs turns interface .pyi files into importable modules that raise NotImplementedError."""
import asyncio
import importlib.util
import inspect
from pathlib import Path

import pytest

from big_brother.stubs import InterfaceError, make_stubs


def write(root: Path, files: dict[str, str]) -> None:
    for rel, text in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def load(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def stub(tmp_path: Path, text: str):
    write(tmp_path / "interface", {"mod.pyi": text})
    make_stubs(tmp_path / "interface", tmp_path / "out")
    return load(tmp_path / "out" / "mod.py")


def test_function_keeps_signature_and_docstring_and_raises(tmp_path):
    mod = stub(tmp_path, 'def add(a: int, b: int = 1) -> int:\n    """Sum."""\n    ...\n')
    assert str(inspect.signature(mod.add)) == "(a: int, b: int = 1) -> int"
    assert mod.add.__doc__ == "Sum."
    with pytest.raises(NotImplementedError, match="add"):
        mod.add(1, 2)


def test_implementation_in_interface_is_stripped(tmp_path):
    mod = stub(tmp_path, "def add(a, b):\n    return a + b\n")
    with pytest.raises(NotImplementedError):
        mod.add(1, 2)


def test_class_members_are_stubbed_with_qualified_names(tmp_path):
    mod = stub(tmp_path, (
        "class Stack:\n"
        "    def __init__(self) -> None: ...\n"
        "    def push(self, x: int) -> None: ...\n"
        "    @property\n"
        "    def size(self) -> int: ...\n"
        "    @staticmethod\n"
        "    def empty() -> 'Stack': ...\n"
        "    class Node:\n"
        "        def value(self) -> int: ...\n"
    ))
    with pytest.raises(NotImplementedError, match=r"Stack\.__init__"):
        mod.Stack()
    s = object.__new__(mod.Stack)
    with pytest.raises(NotImplementedError, match=r"Stack\.push"):
        s.push(1)
    with pytest.raises(NotImplementedError, match=r"Stack\.size"):
        s.size
    with pytest.raises(NotImplementedError, match=r"Stack\.empty"):
        mod.Stack.empty()
    with pytest.raises(NotImplementedError, match=r"Stack\.Node\.value"):
        mod.Stack.Node().value()


def test_async_function_raises_when_awaited(tmp_path):
    mod = stub(tmp_path, "async def fetch(url: str) -> bytes: ...\n")
    with pytest.raises(NotImplementedError, match="fetch"):
        asyncio.run(mod.fetch("x"))


def test_constants_imports_and_dataclasses_survive(tmp_path):
    mod = stub(tmp_path, (
        "from dataclasses import dataclass\n"
        "LIMIT = 10\n"
        "NAMES: list[str] = ['a']\n"
        "COUNT: int\n"
        "@dataclass\n"
        "class Point:\n"
        "    x: int\n"
        "    y: int = 0\n"
    ))
    assert mod.LIMIT == 10
    assert mod.NAMES == ["a"]
    assert not hasattr(mod, "COUNT")
    assert mod.Point(1).x == 1


def test_packages_mirror_the_interface_tree(tmp_path):
    write(tmp_path / "interface", {
        "shapes/__init__.pyi": "",
        "shapes/area.pyi": "def square(side: float) -> float: ...\n",
        "calc.pyi": "def add(a: int, b: int) -> int: ...\n",
        "README.md": "not an interface\n",
    })
    written = make_stubs(tmp_path / "interface", tmp_path / "out")
    assert written == [Path("calc.py"), Path("shapes/__init__.py"), Path("shapes/area.py")]
    assert not (tmp_path / "out" / "README.md").exists()
    assert "Generated by big_brother" in (tmp_path / "out" / "calc.py").read_text()


def test_bad_interface_names_the_file(tmp_path):
    write(tmp_path / "interface", {"bad.pyi": "def broken(:\n"})
    with pytest.raises(InterfaceError, match="bad.pyi"):
        make_stubs(tmp_path / "interface", tmp_path / "out")
