"""Generate importable stubs from interface files.

A target project's `interface/` holds `.pyi` files: signatures, docstrings,
classes and constants, written by the test writer. `make_stubs` turns each into
a `.py` module at the same relative path in which every function and method
body is replaced by `raise NotImplementedError("<qualified name>")`, keeping
the docstring. Everything else (imports, constants, class bodies, decorators)
is kept, so the stubs import cleanly and tests fail only where behavior is
missing. Any implementation that slipped into an interface file is stripped.
"""
from __future__ import annotations

import ast
from pathlib import Path


class InterfaceError(Exception):
    """An interface file could not be parsed."""


class _Stubber(ast.NodeTransformer):
    def __init__(self) -> None:
        self.scope: list[str] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()
        return node

    def _function(self, node):
        name = ".".join([*self.scope, node.name])
        body = []
        if ast.get_docstring(node, clean=False) is not None:
            body.append(node.body[0])
        body.append(ast.parse(f"raise NotImplementedError({name!r})").body[0])
        node.body = body
        return node

    visit_FunctionDef = _function
    visit_AsyncFunctionDef = _function


def stub_source(text: str, name: str = "<interface>") -> str:
    try:
        tree = ast.parse(text, filename=name)
    except SyntaxError as err:
        raise InterfaceError(f"{name}: line {err.lineno}: {err.msg}") from None
    tree = ast.fix_missing_locations(_Stubber().visit(tree))
    return f"# Generated by big_brother.stubs from {name}. Do not edit.\n" + ast.unparse(tree) + "\n"


def make_stubs(interface_dir: Path | str, out_dir: Path | str) -> list[Path]:
    """Write a stub module for every .pyi under interface_dir; return their relative paths."""
    interface_dir, out_dir = Path(interface_dir), Path(out_dir)
    written = []
    for pyi in sorted(interface_dir.rglob("*.pyi")):
        rel = pyi.relative_to(interface_dir).with_suffix(".py")
        source = stub_source(pyi.read_text(), str(pyi.relative_to(interface_dir.parent)))
        target = out_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source)
        written.append(rel)
    return written
